#include "CreateBoard.h"
#include <stdio.h>


void generateBoard(){
    printf("##############################\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#  Bonjour et bienvenue dans #\n"
                   "#  notre labyrinthe infini,  #\n"
                   "#   vous allez experimente   #\n"
                   "#      des niveaux d'une     #\n"
                   "#      difficulte extreme    #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#        Bon chance :)       #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "#                            #\n"
                   "##############################\n");
}